# numpy随机抽样

In [1]:
import numpy as np

## seed
设置seed，使得每次生成的随机数相同

In [2]:
np.random.seed(1024)

## 生成简单随机数

### rand
`rand`产生来自于范围在\[0,1)之间均匀分布的随机数

In [3]:
np.random.rand(2, 3)

array([[0.64769123, 0.99691358, 0.51880326],
       [0.65811273, 0.59906347, 0.75306733]])

### randn
`randn`产生来自于标准正态分布(`N(0, 1)`)的随机数

In [4]:
np.random.randn(2, 3)

array([[ 0.45822365, -0.80933344,  0.86407349],
       [ 0.20170137, -1.87529904, -0.56850693]])

In [5]:
# 生成来自于`N(1, 4)`的随机数
2 * np.random.randn(2, 3) + 1

array([[ 0.86979718,  2.61363332, -0.1556352 ],
       [ 2.14612128,  0.32665008,  1.59401468]])

### randint
`randint`产生指定范围内的随机整数
- 当`high`为None时，产生\[0, `low`)范围内的随机整数
- 当`high`不为None时，产生\[low, high)范围内的随机整数

In [6]:
np.random.randint(1, 10, size=(2, 3))

array([[5, 5, 2],
       [1, 2, 9]])

### random_sample
生成[0, 1)之间的随机浮点数  
下列函数和`random_sample`是等价
- random
- ranf
- sample

In [7]:
np.random.random_sample((2, 3))

array([[0.89657277, 0.64639849, 0.52486889],
       [0.70675401, 0.57266089, 0.8620289 ]])

In [8]:
# 生成[10, 100)之间的随机浮点数
(100 - 10) * np.random.random_sample((2, 3)) + 10

array([[58.94443263, 17.76883445, 71.32518268],
       [27.05357562, 50.01629366, 21.42691165]])

### choice
从给定范围中产生

In [9]:
np.random.choice(np.arange(10), 5)

array([7, 5, 4, 0, 8])

- `reaplce`: 是否放回
- `p`: 设置样本概率

In [10]:
x = np.random.choice([0, 1], 10000, p=[0.2, 0.8])
np.mean(x)

0.8051

## 排列

### shuffle
重新排列数组顺序

In [11]:
a = np.arange(10)
np.random.shuffle(a)
a

array([5, 9, 3, 1, 4, 7, 6, 2, 8, 0])

### permutation
重新排列数组顺序，与`shuffle`作用大致相同，主要有区别是：
- `shuffle`只能传入数组形式参数，而`permutation`还可以传入一个`int`作为参数，当传入`int`参数时，相当于对`numpy.arange(int)`进行重新排列
- `shuffle`只能原地修改，而`permutation`则会返回一个重新排列后的副本(`copy`)。

In [12]:
a = np.arange(10)
a_rearrange = np.random.permutation(a)
a_rearrange

array([7, 6, 1, 5, 4, 8, 3, 0, 2, 9])

## 从不同分布的生成随机数
numpy可以从不同的分布中来产生随机数，具体支持的分布可以在[numpy文档](https://docs.scipy.org/doc/numpy/reference/routines.random.html#distributions)上查询

In [13]:
# gamma分布
np.random.gamma(2, 2, 5)

array([3.01341176, 3.82872498, 2.55084938, 2.63724244, 2.77638998])

In [14]:
# 泊松分布
np.random.poisson(5, 10)

array([9, 5, 5, 6, 2, 2, 5, 3, 6, 3])